name: test-pipeline

# 向 main 分支创建或更新 PR 时触发
on:
  pull_request:
    types:
      - opened
      - synchronize # PR创建或代码更新时触发
    branches:
      - main

jobs:
  # 构建
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: checkout-code
        uses: actions/checkout@v4

      # 安装JDK21
      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # 使用 Temurin 产商的 JDK 版本

      # 配置Maven仓库缓存，避免每次构建时都重新下载依赖
      - name: cache-local-maven-repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 构建并发布到仓库
      - name: build-and-publish
        env:
          isRelease: false
        run: |
          bash .github/workflows/build/buildAndPublish.sh

  # 部署
#  deploy:
#    # 需要 build 执行完后才执行，否则 job 是并行执行的
#    needs: build
#    runs-on: debian-hk-claw-2c2g
#    steps:
#      - name: stop
#        run: |
#          bash .github/workflows/deploy/0-stop.sh
#      - name: uninstall
#        run: |
#          bash .github/workflows/deploy/1-uninstall.sh
#      - name: install
#        run: |
#          bash .github/workflows/deploy/2-install.sh
#      - name: start
#        run: |
#          bash .github/workflows/deploy/3-start.sh
#      - name: check
#        run: |
#          bash .github/workflows/deploy/4-check.sh



